apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-react-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: demo-react-app
  template:
    metadata:
      labels:
        app: demo-react-app
    spec:
      containers:
      - name: demo-react-app
        image: andreanimi/demo-react-app:v1
        resources:
          limits:
            memory: "550Mi"
            cpu: "500m"
        ports:
        - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: demo-react-app
spec:
  type: NodePort
  selector:
    app: demo-react-app
  ports:
  - port: 3050
    targetPort: 3000
    protocol: TCP
    nodePort: 31000
    


